### PR TITLE
Bbradt updates 011724

### PR DESCRIPTION
**Pull request by bbradt**
Updates the following:
```
_data/
  trends.yaml
docs/
  Cluster_queue_information.md
  Log_in_to_the_cluster.md
  SLURM_overview.md
```
changes are mostly focused on updating node names and cluster configuration information.

### CODE REVIEW

**Comment by rsilva8** [comment]
@bbradt 
The recommendation from IT (see [ARCTIC wiki](https://arcwiki.rs.gsu.edu/en/home/ssh/generating-keys)) is to use `-t ed25519` encryption for SSH key generation.
iirc, RSA256 is no longer considered safe enough.

Also, the recommendation for the login node is to use arclogin.rs.gsu.edu as the address (see [ARCTIC wiki](https://arcwiki.rs.gsu.edu/en/home/ssh/signing-in)).
IT had a setup (not sure it is still the case) that would reroute users to different login nodes on the fly based on load.
Using a different address from arclogin.rs.gsu.edu bypasses that feature.

I get that some people have not been able to connect with this address.
I'm sharing my SSH config (for MAC) in case it may help with that (ignore forwards, of course):

All else looks good!

```
Host *
    AddKeysToAgent yes
    IgnoreUnknown UseKeychain
    UseKeychain yes
    ForwardAgent yes
    ServerAliveInterval 180
    ServerAliveCountMax 3
    TCPKeepAlive yes
    user rsilva
    ForwardX11Trusted yes
    ForwardX11 yes
    XAuthLocation /opt/X11/bin/xauth

host arclogin
    HostName arclogin.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    CertificateFile /Users/rsilva/.ssh/id_rsilva-cert.pub

host arctrdlogin001
    HostName arctrdlogin001.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    CertificateFile /Users/rsilva/.ssh/id_rsilva-cert.pub

host arctrdlogin01
    HostName arctrdlogin01.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    CertificateFile /Users/rsilva/.ssh/id_rsilva-cert.pub

host arctrdlogin02
    HostName arctrdlogin02.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    CertificateFile /Users/rsilva/.ssh/id_rsilva-cert.pub

host arctrdlogin03
    HostName arctrdlogin03.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    CertificateFile /Users/rsilva/.ssh/id_rsilva-cert.pub

host arctrdgndev101
    HostName arctrdgndev101.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    CertificateFile /Users/rsilva/.ssh/id_rsilva-cert.pub
    LocalForward 18161 localhost:18161
    LocalForward 18162 localhost:18162
    LocalForward 18167 localhost:18167

host arctrdagn019
    HostName arctrdagn019.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    CertificateFile /Users/rsilva/.ssh/id_rsilva-cert.pub
    LocalForward 18161 localhost:18161
    LocalForward 18162 localhost:18162
    LocalForward 18167 localhost:18167

host arctrdcn017
    HostName arctrdcn017.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    CertificateFile /Users/rsilva/.ssh/id_rsilva-cert.pub
    LocalForward 18161 localhost:18161
    LocalForward 18162 localhost:18162
    LocalForward 18167 localhost:18167

host arctrdcn018
    HostName arctrdcn018.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    CertificateFile /Users/rsilva/.ssh/id_rsilva-cert.pub
    LocalForward 18161 localhost:18161
    LocalForward 18162 localhost:18162
    LocalForward 18167 localhost:18167

host arctrdhm001
    HostName arctrdhm001.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdhm002
    HostName arctrdhm002.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdhm003
    HostName arctrdhm003.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrddgxa001
    HostName arctrddgxa001.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva

host arctrddgx002
    HostName arctrddgx002.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva

host arctrddgx003
    HostName arctrddgx003.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva

host arctrddgx004
    HostName arctrddgx004.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva

host arctrddgxa001
    HostName arctrddgxa001.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva

host arctrdgn001
    HostName arctrdgn001.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva

host arctrdgn002
    HostName arctrdgn002.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva

host arctrdagn001
    HostName arctrdagn001.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn002
    HostName arctrdagn002.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn003
    HostName arctrdagn003.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn004
    HostName arctrdagn004.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn005
    HostName arctrdagn005.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn006
    HostName arctrdagn006.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn007
    HostName arctrdagn007.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn008
    HostName arctrdagn008.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn009
    HostName arctrdagn009.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn010
    HostName arctrdagn010.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn011
    HostName arctrdagn011.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn012
    HostName arctrdagn012.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn013
    HostName arctrdagn013.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn014
    HostName arctrdagn014.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn015
    HostName arctrdagn015.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn016
    HostName arctrdagn016.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn017
    HostName arctrdagn017.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn018
    HostName arctrdagn018.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn019
    HostName arctrdagn019.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdagn020
    HostName arctrdagn020.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn001
    HostName arctrdcn001.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva

host arctrdcn002
    HostName arctrdcn002.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn003
    HostName arctrdcn003.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn004
    HostName arctrdcn004.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn005
    HostName arctrdcn005.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn006
    HostName arctrdcn006.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn007
    HostName arctrdcn007.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn008
    HostName arctrdcn008.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn009
    HostName arctrdcn009.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn010
    HostName arctrdcn010.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn011
    HostName arctrdcn011.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn012
    HostName arctrdcn012.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn013
    HostName arctrdcn013.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn014
    HostName arctrdcn014.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn015
    HostName arctrdcn015.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn016
    HostName arctrdcn016.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn017
    HostName arctrdcn017.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn018
    HostName arctrdcn018.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn019
    HostName arctrdcn019.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

host arctrdcn020
    HostName arctrdcn020.rs.gsu.edu
    IdentityFile /Users/rsilva/.ssh/id_rsilva
    LocalForward 18167 localhost:18167

```

**Comment by bbradt** [comment]
@rsilva8 
re the `-t ed25519` flag. I had several users report this flag does not work for them. I am not sure if it is an OSX issue or what. I can add it back in, but we need a recommendation for when this does not work. 

re the login node name. Did we narrow down why this does not work for some users? I am one of the users for whom it did not work previously - the only address which works is arctrdlogin001.

**Comment by bbradt** [comment]
FYI I've verified the alias arclogin.rs.gsu.edu does not work. Here is the top of my config:
```
Host *
    AddKeysToAgent yes
    IgnoreUnknown UseKeychain
    UseKeychain yes
    ForwardAgent yes
    ServerAliveInterval 180
    ServerAliveCountMax 3
    TCPKeepAlive yes
    user rsilva
    ForwardX11Trusted yes
    ForwardX11 yes
    XAuthLocation /opt/X11/bin/xauth

Host arclogin
  HostName arclogin.rs.gsu.edu
  User bbaker43
  IdentityFile ~/.ssh/id_bbaker43
  CertificateFile ~/.ssh/id_bbaker43-cert.pub
```

**Comment by rsilva8** [comment]
@bbradt 
re the flag: it's speculative, but maybe an outdated version of SSH? If not that, then I'd loop IT in.

re login name: if it works one way and not the other, then that's probably a ticket to IT.

**Comment by rsilva8** [comment]
AddKeysToAgent yes
    IgnoreUnknown UseKeychain
    UseKeychain yes
    XAuthLocation /opt/X11/bin/xauth
    
These keys are for MAC only... irrc, Windows does not use keys

**Comment by bbradt** [comment]
I'm not sure what made the difference. I copied the TCPKeepAlive commands as well and it worked afterwards, but I just removed them and it now works 🤷 . I think we should just recommend your config and it should solve the issue

**Comment by bbradt** [comment]
@rsilva8 I have made updates to address your comments - if you think all else is good, I think we can go ahead and merge?

**Pull request merged**
